import type { Metadata } from "next";
import "../public/globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Navbar  />
        {children}
      </body>
    </html>
  );
}
